### PR TITLE
Use a set for the frontier

### PR DESCRIPTION
**Pull request by splch**
Would it make more sense to use a set for the frontier?

### CODE REVIEW

**Comment by crista** [comment]
@lordnahor can I merge this, or was there a good reason for using a list?

**Comment by splch** [comment]
I'm not sure if there's any benefits of using a list... I think a set would be more performant.

**Comment by lordnahor** [comment]
There was a reason I used a list (I did try sets). The difference in performance between the two is negligible (no lookups). But I wanted to preserve insertion order --> The urls to be downloaded are picked up from the top of the list and the urls scraped are added at the end.

When urls are scraped from a webpage, usually all urls from the same domain tend to get added together. When a student is observing urls to see if they are "bad" urls or not it makes sense for these urls to tend to come together. In fact if the same domain is being downloaded for the last few hours, they could stop it and block that domain.

In my experience, with sets not preserving order, this manual pattern matching is much harder to do.

I'd like to keep it a list. :)

**Comment by splch** [comment]
> There was a reason I used a list (I did try sets). The difference in performance between the two is negligible (no lookups). But I wanted to preserve insertion order --> The urls to be downloaded are picked up from the top of the list and the urls scraped are added at the end.
> 
> When urls are scraped from a webpage, usually all urls from the same domain tend to get added together. When a student is observing urls to see if they are "bad" urls or not it makes sense for these urls to tend to come together. In fact if the same domain is being downloaded for the last few hours, they could stop it and block that domain.
> 
> In my experience, with sets not preserving order, this manual pattern matching is much harder to do.
> 
> I'd like to keep it a list. :)

I used this exact feature to ignore some links in my crawler 😅 Thanks for explaining! It makes a lot of sense now.

**Pull request closed without merging**
